project:
  type: website
  output-dir: docs

website:
  title: "disease-surveillance-workshop"
  sidebar:
    style: "docked"
    search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mapping.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



