project:
  type: book
  output-dir: docs

book:
  title: "Disease Surveillance Workshop"
  search: true
  site-url: https://siobhonlegan.com/disease-surveillance-workshop/
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - whyRandRStudio.qmd
        - merging-data-introduction.qmd
    - part: "Mapping"
      chapters:
        - mapping-introduction.qmd
        - mapping-application.qmd
    - part: "Data Integration & Visualization"
      chapters:
        - phylogenetics.qmd
        - omicsIntegration.qmd
    - part: "Resources"
      chapters:
        - resources.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true



