---
title: "Mapping Exercise"
---


https://epirhandbook.com/en/new_pages/gis.html

https://epirhandbook.com/en/new_pages/gis.html#contoured-density-heatmaps

```         
#install.packages("pacman")
```

```{r}
# pacman::p_load(
#   rio,           # to import data
#   here,          # to locate files
#   tidyverse,     # to clean, handle, and plot the data (includes ggplot2 package)
#   sf,            # to manage spatial data using a Simple Feature format
#   tmap,          # to produce simple maps, works for both interactive and static maps
#   janitor,       # to clean column names
#   OpenStreetMap, # to add OSM basemap in ggplot map
#   spdep          # spatial statistics
#   )

pacman::p_load(
  rio,           # to import data
  tidyverse,     # to clean, handle, and plot the data (includes ggplot2 package)
  OpenStreetMap # to add OSM basemap in ggplot map
  )
```

Download case data https://epirhandbook.com/en/new_pages/gis.html#sample-case-data

```{r}
# import clean case linelist
linelist <- import("data/linelist_cleaned.rds")  
```

```{r}
# Create sf object
linelist_sf <- linelist %>%
     sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)
```


Next we select a random sample of 1000 rows using sample() from base R.

```{r}
# generate 1000 random row numbers, from the number of rows in linelist
sample_rows <- sample(nrow(linelist), 1000)

# subset linelist to keep only the sample rows, and all columns
linelist <- linelist[sample_rows,]
```

```{r}
# load package
pacman::p_load(OpenStreetMap)

# Fit basemap by range of lat/long coordinates. Choose tile type
map <- OpenStreetMap::openmap(
  upperLeft = c(max(linelist$lat, na.rm=T), max(linelist$lon, na.rm=T)),   # limits of basemap tile
  lowerRight = c(min(linelist$lat, na.rm=T), min(linelist$lon, na.rm=T)),
  zoom = NULL,
  type = c("osm", "stamen-toner", "stamen-terrain", "stamen-watercolor", "esri","esri-topo")[1])
```

```{r}
autoplot.OpenStreetMap(map)
```

```{r}
# Projection WGS84
map_latlon <- openproj(map, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
```

```{r}
# Plot map. Must use "autoplot" in order to work with ggplot
autoplot.OpenStreetMap(map_latlon)
```

```{r}
# Plot map. Must be autoplotted to work with ggplot
autoplot.OpenStreetMap(map_latlon)+                 # begin with the basemap
  geom_point(                                       # add xy points from linelist lon and lat columns 
    data = linelist,                                
    aes(x = lon, y = lat),
    size = 1, 
    alpha = 0.5,
    show.legend = FALSE) +                          # drop legend entirely
  labs(x = "Longitude",                             # titles & labels
       y = "Latitude",
       title = "Cumulative cases")
```

```{r}
# begin with the basemap
autoplot.OpenStreetMap(map_latlon)+
  
  # add the density plot
  ggplot2::stat_density_2d(
        data = linelist,
        aes(
          x = lon,
          y = lat,
          fill = ..level..,
          alpha = ..level..),
        bins = 10,
        geom = "polygon",
        contour_var = "count",
        show.legend = F) +                          
  
  # specify color scale
  scale_fill_gradient(low = "black", high = "red")+
  
  # labels 
  labs(x = "Longitude",
       y = "Latitude",
       title = "Distribution of cumulative cases")
```

```{r}
# Extract month of onset
linelist <- linelist %>% 
  mutate(date_onset_ym = format(date_onset, "%Y-%m"))

# Examine the values 
table(linelist$date_onset_ym, useNA = "always")
```

```{r}
# packages
pacman::p_load(OpenStreetMap, tidyverse)

# begin with the basemap
autoplot.OpenStreetMap(map_latlon)+
  
  # add the density plot
  ggplot2::stat_density_2d(
        data = linelist,
        aes(
          x = lon,
          y = lat,
          fill = ..level..,
          alpha = ..level..),
        bins = 10,
        geom = "polygon",
        contour_var = "count",
        show.legend = F) +                          
  
  # specify color scale
  scale_fill_gradient(low = "black", high = "red")+
  
  # labels 
  labs(x = "Longitude",
       y = "Latitude",
       title = "Distribution of cumulative cases over time")+
  
  # facet the plot by month-year of onset
  facet_wrap(~ date_onset_ym, ncol = 4)               
```

https://simplemaps.com/gis/country/my#admin1

```{r}
library(sf)
library(tmap)
nc = read_sf("data/my_shp/my.shp")

#nc = read_sf("data/mys_adm_unhcr_20210211_shp/mys_admbnda_adm1_unhcr_20210211.shp")

tm_shape(nc) +               # admin boundaries shapefile
  tm_polygons(col = "name")+    # show polygons in light grey
  tm_borders(col = "red",      # show borders with color and line weight
             lwd = 2) +
  tm_text("name") 

```

```{r}

ggplot(data=nc) + 
  geom_sf(aes(fill=name))

```


```{r}
tmap_mode("view")
tm_shape(nc) +               # admin boundaries shapefile
  tm_polygons(col = "#F7F7F7")+    # show polygons in light grey
  tm_borders(col = "#000000",      # show borders with color and line weight
             lwd = 2) +
  tm_text("name") 
```
